### ISSUE TITLE
After updating to 0.90 switch on/off does not work anymore.

### ISSUE THREAD

**Issue by ernout** [daemondazz/homeassistant-displays#10]
Switch on/off generates this error:

2019-03-30 12:05:44 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File “/usr/src/app/homeassistant/core.py”, line 1138, in async_call
self._execute_service(handler, service_call))
File “/usr/src/app/homeassistant/core.py”, line 1160, in _execute_service
await handler.func(service_call)
File “/config/custom_components/display/init.py”, line 82, in async_handle_display_service
for display in target_displays:
TypeError: ‘coroutine’ object is not iterable

**Comment by GuruPG** [comment]
I'm getting the same issue:

2019-04-01 09:18:33 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1789586032] 'coroutine' object is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 122, in handle_call_service
    connection.context(msg))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1138, in async_call
    self._execute_service(handler, service_call))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1160, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/display/__init__.py", line 82, in async_handle_display_service
    for display in target_displays:
TypeError: 'coroutine' object is not iterable

**Comment by plapointe6** [comment]
Also the same issue in my side : 
```
2019-04-07 15:35:19 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1880726320] 'coroutine' object is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 122, in handle_call_service
    connection.context(msg))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1138, in async_call
    self._execute_service(handler, service_call))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1160, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/display/__init__.py", line 82, in async_handle_display_service
    for display in target_displays:
TypeError: 'coroutine' object is not iterable
```

**Comment by mouth4war** [comment]
Heres another error

````ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1625240464] 'coroutine' object is not iterable
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/websocket_api/commands.py", line 122, in handle_call_service
    connection.context(msg))
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/core.py", line 1138, in async_call
    self._execute_service(handler, service_call))
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/core.py", line 1160, in _execute_service
    await handler.func(service_call)
  File "/home/homeassistant/.homeassistant/custom_components/display/__init__.py", line 82, in async_handle_display_service
    for display in target_displays:
TypeError: 'coroutine' object is not iterable
/usr/local/lib/python3.6/asyncio/base_events.py:1427: RuntimeWarning: coroutine 'EntityComponent.async_extract_from_service' was never awaited
  handle = None  # Needed to break cycles when an exception occurs.

**Comment by plapointe6** [comment]
I found a temporary fix, might be useful to make it works while waiting for a permanent fix.

Add this switch to your configuration.yaml, replacing PASSWORD with your Fully Kiosk password and 127.0.0.1 with your Fully Kiosk IP.

```yaml
switch:
  - platform: command_line
    switches:
      fkiosk_screen:
        command_on: "/usr/bin/curl -X POST 'http://127.0.0.1:2323/?cmd=screenOn&type=json&password=PASSWORD'"
        command_off: "/usr/bin/curl -X POST 'http://127.0.0.1:2323/?cmd=screenOff&type=json&password=PASSWORD'"
        command_state: '/usr/bin/curl --silent -X GET "http://127.0.0.1:2323/?password=PASSWORD" |grep "Screen status" |grep "on\|off" |sed "s/<[^>]*>//g" |sed "s/Screen status//g" |sed "s/Turn on//g" |sed "s/Turn off//g"'
        value_template: '{{ value == "on" }}'
        friendly_name: Display
```
