### ISSUE TITLE
TurnOn not working

### ISSUE THREAD

**Issue by MPopti0n** [daemondazz/homeassistant-displays#3]
The default switch added to HomeAssistant frontend can successfully turn `off` the screen but not `on`. When I click on the switch the screen turn `off` and the switch immediately go back to the `on` position (not the screen) and If I use the `display.turnon` service in a script it dosen't work either.

- Home Assistant ver.  `0.68.1` running on RPi3
- [x] The permission / tutorial on your GitHub have been followed
- [x] The file from your GitHub on my HomeAssistant are up-to-date

Config file : 

```
display:
  - platform: fully_kiosk
    name: Android Tablet
    host: 192.168.1.193
    password: !secret general_password_3
```
