### ISSUE TITLE
Issues with version 88.1

### ISSUE THREAD

**Issue by GuruPG** [daemondazz/homeassistant-displays#7]
Hello,

am having issues with the component in the new version of Home assistant.
As its a custom component they refereed me to you.

**Home Assistant release with the issue:**
0.88.1
**Last working Home Assistant release (if known):**
0.87

**Operating environment (Hass.io/Docker/Windows/etc.):**
Hass.io

**Component/platform:**
https://www.home-assistant.io/custom_components/display/fully_kiosk

**Description of problem:**
As of 0.88.1 a warning is shown:

> Your configuration contains extra keys that the platform does not support (but were silently accepted before 0.88). Please find and remove the following.This will become a breaking change.
> 
> * [name], [host], [password].  (See /config/configuration.yaml, line 70).
> * [name], [host], [password].  (See /config/configuration.yaml, line 74).
> * [name], [host], [password].  (See /config/configuration.yaml, line 78).
> * [name], [host], [password].  (See /config/configuration.yaml, line 82).

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**

```yaml
#tablet battery
display:
  - platform: fully_kiosk
    name: Dining Tablet
    host: '192.168.0.179'
    password: !secret http_password
  - platform: fully_kiosk
    name: Lobby Tablet
    host: '192.168.0.168'
    password: !secret http_password
  - platform: fully_kiosk
    name: TV Tablet
    host: '192.168.0.185'
    password: !secret http_password
  - platform: fully_kiosk
    name: 'Nexus 10 Tablet'
    host: '192.168.0.183'
    password: !secret http_password

```
